# Generated by Django 2.2 on 2019-07-15 04:09

import budget.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailgun_api_key', models.CharField(blank=True, max_length=255)),
                ('mailgun_domain', models.CharField(blank=True, max_length=255)),
                ('mailgun_api_url', models.CharField(blank=True, max_length=255)),
                ('email_noreply', models.CharField(blank=True, max_length=255)),
                ('email_job', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Настройки почтового сервиса',
                'verbose_name_plural': 'Настройки почтового сервиса',
            },
            bases=(budget.mixins.SingleInstanceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConfigurationFireBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_key_server', models.CharField(blank=True, max_length=255)),
                ('firebase_url_request', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Настройки FireBase сервиса',
                'verbose_name_plural': 'Настройки FireBase сервиса',
            },
            bases=(budget.mixins.SingleInstanceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PushTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('new_message', 'new_message')], max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('lang', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='ru-ru', max_length=2)),
            ],
            options={
                'verbose_name': 'Шаблоны push уведомлений',
                'verbose_name_plural': 'Шаблоны push уведомлений',
                'unique_together': {('event', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('password_reset', 'password_reset'), ('password_reset_complete', 'password_reset_complete'), ('invite', 'invite')], max_length=255)),
                ('subj', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('html', models.TextField()),
                ('lang', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='ru-ru', max_length=2)),
            ],
            options={
                'verbose_name': 'Шаблоны писем',
                'verbose_name_plural': 'Шаблоны писем',
                'unique_together': {('event', 'lang')},
            },
        ),
    ]
